### PR TITLE
Port to WebKit2Gtk as WebKitGtk is no longer supported

### PR DESCRIPTION
**Pull request by XRevan86**
WebKitGtk is a [security hazard](https://lwn.net/Articles/730185), so this merge request ports birdie to WebKit2Gtk (dropping WebKitGtk support).

### CODE REVIEW

**Comment by SolarAquarion** [comment]
It doesn't build

**Comment by XRevan86** [comment]
Oh, missed a spot:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -89,7 +89,7 @@ set(CFLAGS
 )
 
 set(BIRDIE_PACKAGES
-    gtk+-3.0 gtksourceview-3.0 granite libsoup-2.4 gee-0.8 rest-0.7 json-glib-1.0 libnotify>=0.7.5 libcanberra>=0.28 gdk-x11-3.0 webkitgtk-3.0 sqlite3 xtst purple posix ${EXTRA_PACKAGES}
+    gtk+-3.0 gtksourceview-3.0 granite libsoup-2.4 gee-0.8 rest-0.7 json-glib-1.0 libnotify>=0.7.5 libcanberra>=0.28 gdk-x11-3.0 webkit2gtk-4.0 sqlite3 xtst purple posix ${EXTRA_PACKAGES}
 )
 
 set(VALAC_OPTIONS
```
Fixed now.

**Comment by SolarAquarion** [comment]
Push to branch master

**Comment by XRevan86** [comment]
But I did.

**Comment by SolarAquarion** [comment]
https://github.com/XRevan86/birdie

hasn't been updated

**Comment by SolarAquarion** [comment]
error: Package `webkitgtk-3.0' not found in specified Vala API directories or GObject-Introspection GIR directories
make[2]: *** [src/CMakeFiles/birdie.dir/build.make:103: src/main.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: src/CMakeFiles/birdie.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().

**Comment by SolarAquarion** [comment]
home/solaraquarion/birdie/src/Widgets/Notebook.vala:20.29-20.58: error: The type name `Granite.Widgets.StaticNotebook' could not be found
    public class Notebook : Granite.Widgets.StaticNotebook {
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ivonunes** [comment]
Thank you, I've merged this into the master branch now.

**Comment by XRevan86** [comment]
@ivonunes, ho, mojosas!

**Pull request merged**
